import { projectCollaboratorParticipantTypes } from "../project-collaborator-participant-types";

export const permissionRoleValues = [
  "SUPER_ADMIN",
  "ADMIN",
  "COLLABORATOR",
] as const;

export type PermissionRole = (typeof permissionRoleValues)[number];

export const collaboratorTypeValues = projectCollaboratorParticipantTypes;

export type CollaboratorTypeValue = (typeof collaboratorTypeValues)[number];

export const moduleAccessValues = ["FULL", "LIMITED", "NONE"] as const;

export type ModuleAccessValue = (typeof moduleAccessValues)[number];

export const permissionProfileTypeValues = [
  "role",
  "collaboratorType",
  "accessPreset",
] as const;

export type PermissionProfileType = (typeof permissionProfileTypeValues)[number];

// Permission keys describe stable business rules. Server actions and routes should
// resolve access through these keys rather than coupling checks to URL paths.
export const permissionCatalog = {
  dashboard: [
    "dashboard.view",
    "dashboard.viewProjectCounts",
    "dashboard.viewRecentProjects",
  ],
  project: [
    "project.list",
    "project.view",
    "project.create",
    "project.update",
    "project.delete",
    "project.viewBudget",
    "project.updateBudget",
    "project.viewParticipants",
    "project.manageCollaborators",
  ],
  stage: [
    "stage.view",
    "stage.acceptBrief",
    "stage.submitWork",
    "stage.reviewSubmission",
    "stage.requestRevision",
    "stage.markSubmissionComplete",
    "stage.markStageComplete",
    "stage.updateBudget",
    "stage.updateTimeline",
  ],
  chat: [
    "chat.view",
    "chat.comment",
    "chat.uploadAttachment",
    "chat.mentionUsers",
  ],
  compare: [
    "compare.view",
    "compare.comment",
  ],
  calendar: [
    "calendar.view",
    "calendar.create",
    "calendar.update",
    "calendar.delete",
    "calendar.assignParticipants",
  ],
  collaboration: [
    "collaboration.viewDirectory",
    "collaboration.createUser",
    "collaboration.updateUser",
    "collaboration.deleteGlobal",
    "collaboration.manageModuleAccess",
    "collaboration.pauseVisibility",
  ],
  library: [
    "library.view",
    "library.deleteFile",
  ],
  archive: [
    "archive.view",
    "archive.download",
  ],
  completion: [
    "completion.viewChecklist",
    "completion.setApprovalRequired",
    "completion.uploadApprovalProof",
    "completion.setCopyrightTransfer",
    "completion.uploadCopyrightDocument",
    "completion.uploadInvoice",
  ],
  settings: [
    "settings.viewOwnProfile",
    "settings.updateOwnProfile",
    "settings.changeOwnPassword",
    "settings.viewMasterData",
    "settings.manageMasterData",
    "settings.deleteMasterData",
    "settings.managePermissions",
  ],
  notification: [
    "notification.view",
    "notification.markRead",
  ],
  file: [
    "file.view",
    "file.download",
    "file.delete",
    "file.favorite",
    "file.uploadSubmission",
  ],
} as const;

export type PermissionGroup = keyof typeof permissionCatalog;

export type PermissionKey = (typeof permissionCatalog)[PermissionGroup][number];

export type ModuleName =
  | "dashboard"
  | "project"
  | "calendar"
  | "collaboration"
  | "library"
  | "archive"
  | "settings"
  | "notification"
  | "file";

export type PermissionDefinitionRecord = {
  key: PermissionKey;
  label: string;
  description: string;
  group: PermissionGroup;
  isSystem: boolean;
  moduleGated: boolean;
  hardRule: boolean;
};

export type PermissionGroupDefinition = {
  id: PermissionGroup;
  title: string;
  description: string;
};

export const permissionGroupDefinitions: readonly PermissionGroupDefinition[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    description: "High-level dashboard visibility and summaries.",
  },
  {
    id: "project",
    title: "Projects",
    description: "Core project access and management.",
  },
  {
    id: "stage",
    title: "Stages",
    description: "Stage workflow actions within projects.",
  },
  {
    id: "chat",
    title: "Chat",
    description: "Project discussion and collaboration actions.",
  },
  {
    id: "compare",
    title: "Compare",
    description: "Artwork comparison review and commenting.",
  },
  {
    id: "file",
    title: "Files",
    description: "Project file, download, and submission actions.",
  },
  {
    id: "library",
    title: "Library",
    description: "Shared reference library access.",
  },
  {
    id: "archive",
    title: "Archives",
    description: "Archived project visibility and downloads.",
  },
  {
    id: "completion",
    title: "Completion",
    description: "Project completion workflow controls.",
  },
  {
    id: "collaboration",
    title: "Collaboration",
    description: "Collaborator directory and access management.",
  },
  {
    id: "calendar",
    title: "Calendar",
    description: "Calendar visibility and event management.",
  },
  {
    id: "notification",
    title: "Notifications",
    description: "Notification center access.",
  },
  {
    id: "settings",
    title: "Settings",
    description: "User settings and administrative controls.",
  },
] as const;

export const permissionDefinitions: readonly PermissionDefinitionRecord[] = [
  {
    key: "dashboard.view",
    label: "Can view dashboard",
    description: "Allows the user to access the main dashboard page.",
    group: "dashboard",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "dashboard.viewProjectCounts",
    label: "Can view project counts",
    description: "Allows the user to see dashboard project summary counts.",
    group: "dashboard",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "dashboard.viewRecentProjects",
    label: "Can view recent projects",
    description: "Allows the user to see recent project cards on the dashboard.",
    group: "dashboard",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "project.list",
    label: "Can list projects",
    description: "Allows the user to open project listing surfaces.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "project.view",
    label: "Can view projects",
    description: "Allows the user to open accessible project detail pages.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "project.create",
    label: "Can create project",
    description: "Allows the user to create new projects.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "project.update",
    label: "Can edit project",
    description: "Allows the user to update existing projects they can manage.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "project.delete",
    label: "Can delete project",
    description: "Allows the user to delete projects when no other hard restriction blocks it.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "project.viewBudget",
    label: "Can view project budget",
    description: "Allows the user to view project budget fields when owner-only rules allow it.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "project.updateBudget",
    label: "Can update project budget",
    description: "Allows the user to edit project budget fields when owner-only rules allow it.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "project.viewParticipants",
    label: "Can view project participants",
    description: "Allows the user to view collaborators and assignees for accessible projects.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "project.manageCollaborators",
    label: "Can manage project collaborators",
    description: "Allows the user to update project collaborator assignments.",
    group: "project",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.view",
    label: "Can view stages",
    description: "Allows the user to see project stage records.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.acceptBrief",
    label: "Can accept brief",
    description: "Allows the user to accept and start a stage brief when executor rules allow it.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.submitWork",
    label: "Can submit work",
    description: "Allows the user to submit stage work when executor rules allow it.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.reviewSubmission",
    label: "Can review submission",
    description: "Allows the user to review stage submissions when project ownership rules allow it.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.requestRevision",
    label: "Can request revision",
    description: "Allows the user to request submission revisions when project ownership rules allow it.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.markSubmissionComplete",
    label: "Can mark submission complete",
    description: "Allows the user to mark a submission complete when review ownership rules allow it.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.markStageComplete",
    label: "Can mark stage complete",
    description: "Allows the user to complete a stage when project ownership rules allow it.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.updateBudget",
    label: "Can update stage budget",
    description: "Allows the user to change stage budgets when ownership rules allow it.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "stage.updateTimeline",
    label: "Can update stage timeline",
    description: "Allows the user to adjust planned stage dates.",
    group: "stage",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "chat.view",
    label: "Can view chat",
    description: "Allows the user to open project chat and history surfaces.",
    group: "chat",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "chat.comment",
    label: "Can add comments",
    description: "Allows the user to add project chat comments.",
    group: "chat",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "chat.uploadAttachment",
    label: "Can upload attachments",
    description: "Allows the user to upload comment attachments in project chat.",
    group: "chat",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "chat.mentionUsers",
    label: "Can mention users",
    description: "Allows the user to mention collaborators in project chat.",
    group: "chat",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "compare.view",
    label: "Can view compare",
    description: "Allows the user to open project comparison screens.",
    group: "compare",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "compare.comment",
    label: "Can comment in compare",
    description: "Allows the user to leave comments in comparison views.",
    group: "compare",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "calendar.view",
    label: "Can view calendar",
    description: "Allows the user to open the calendar module.",
    group: "calendar",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "calendar.create",
    label: "Can create calendar event",
    description: "Allows the user to create calendar events.",
    group: "calendar",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "calendar.update",
    label: "Can update calendar event",
    description: "Allows the user to edit calendar events.",
    group: "calendar",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "calendar.delete",
    label: "Can delete calendar event",
    description: "Allows the user to delete calendar events.",
    group: "calendar",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "calendar.assignParticipants",
    label: "Can assign calendar participants",
    description: "Allows the user to assign collaborators to calendar events.",
    group: "calendar",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "collaboration.viewDirectory",
    label: "Can view collaborators",
    description: "Allows the user to open the collaborator directory.",
    group: "collaboration",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "collaboration.createUser",
    label: "Can invite collaborators",
    description: "Allows the user to create collaborator accounts and invitations.",
    group: "collaboration",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "collaboration.updateUser",
    label: "Can update collaborators",
    description: "Allows the user to update collaborator account details and access.",
    group: "collaboration",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "collaboration.deleteGlobal",
    label: "Can remove collaborators",
    description: "Allows the user to delete collaborator accounts globally.",
    group: "collaboration",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "collaboration.manageModuleAccess",
    label: "Can change collaborator type/access",
    description: "Allows the user to change collaborator type and module access assignments.",
    group: "collaboration",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "collaboration.pauseVisibility",
    label: "Can pause collaborator visibility",
    description: "Allows the user to pause project collaborator chat visibility.",
    group: "collaboration",
    isSystem: true,
    moduleGated: false,
    hardRule: true,
  },
  {
    key: "library.view",
    label: "Can view library",
    description: "Allows the user to open the library module.",
    group: "library",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "library.deleteFile",
    label: "Can delete library files",
    description: "Allows the user to remove files from the library when file ownership rules allow it.",
    group: "library",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "archive.view",
    label: "Can view archives",
    description: "Allows the user to open the archives module.",
    group: "archive",
    isSystem: true,
    moduleGated: true,
    hardRule: false,
  },
  {
    key: "archive.download",
    label: "Can download archive files",
    description: "Allows the user to download accessible archive files.",
    group: "archive",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "completion.viewChecklist",
    label: "Can view completion checklist",
    description: "Allows the user to open the project completion workflow.",
    group: "completion",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "completion.setApprovalRequired",
    label: "Can set approval required",
    description: "Allows the user to update approval requirements when ownership rules allow it.",
    group: "completion",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "completion.uploadApprovalProof",
    label: "Can upload approval proof",
    description: "Allows the user to upload completion approval proof documents.",
    group: "completion",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "completion.setCopyrightTransfer",
    label: "Can set copyright transfer",
    description: "Allows the user to manage copyright transfer settings when ownership rules allow it.",
    group: "completion",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "completion.uploadCopyrightDocument",
    label: "Can upload copyright document",
    description: "Allows the user to upload copyright transfer documents.",
    group: "completion",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "completion.uploadInvoice",
    label: "Can upload invoice",
    description: "Allows the user to upload invoice documents when ownership rules allow it.",
    group: "completion",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "settings.viewOwnProfile",
    label: "Can view settings",
    description: "Allows the user to open their settings page.",
    group: "settings",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "settings.updateOwnProfile",
    label: "Can edit own profile",
    description: "Allows the user to update their own profile information.",
    group: "settings",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "settings.changeOwnPassword",
    label: "Can change own password",
    description: "Allows the user to update their own password.",
    group: "settings",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "settings.viewMasterData",
    label: "Can view master data",
    description: "Allows the user to view project master data surfaces.",
    group: "settings",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "settings.manageMasterData",
    label: "Can manage master data",
    description: "Allows the user to update project master data values.",
    group: "settings",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "settings.deleteMasterData",
    label: "Can delete master data",
    description: "Allows the user to remove project master data values.",
    group: "settings",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "settings.managePermissions",
    label: "Can manage permissions",
    description: "Allows the user to configure permission profiles.",
    group: "settings",
    isSystem: true,
    moduleGated: false,
    hardRule: true,
  },
  {
    key: "notification.view",
    label: "Can view notifications",
    description: "Allows the user to open the notification center.",
    group: "notification",
    isSystem: true,
    moduleGated: false,
    hardRule: false,
  },
  {
    key: "notification.markRead",
    label: "Can mark notifications read",
    description: "Allows the user to mark their own notifications as read.",
    group: "notification",
    isSystem: true,
    moduleGated: false,
    hardRule: true,
  },
  {
    key: "file.view",
    label: "Can view files",
    description: "Allows the user to view project files they can access.",
    group: "file",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "file.download",
    label: "Can download files",
    description: "Allows the user to download project files they can access.",
    group: "file",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "file.delete",
    label: "Can delete files",
    description: "Allows the user to delete project files when ownership rules allow it.",
    group: "file",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "file.favorite",
    label: "Can favorite files",
    description: "Allows the user to favorite project files.",
    group: "file",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
  {
    key: "file.uploadSubmission",
    label: "Can upload submissions",
    description: "Allows the user to upload project submissions or assets.",
    group: "file",
    isSystem: true,
    moduleGated: true,
    hardRule: true,
  },
] as const;

export const permissionDefinitionMap = Object.fromEntries(
  permissionDefinitions.map((definition) => [definition.key, definition]),
) as Record<PermissionKey, PermissionDefinitionRecord>;

export const contextOnlyPermissionKeys = [
  "project.viewBudget",
  "project.updateBudget",
] as const satisfies PermissionKey[];

export type ContextOnlyPermissionKey = (typeof contextOnlyPermissionKeys)[number];

export const hardRulePermissionKeys = permissionDefinitions
  .filter((definition) => definition.hardRule)
  .map((definition) => definition.key) as PermissionKey[];

export const allPermissionKeys = Object.values(permissionCatalog).flat() as PermissionKey[];

export const permissionModuleMap: Record<PermissionKey, ModuleName> = {
  "dashboard.view": "dashboard",
  "dashboard.viewProjectCounts": "project",
  "dashboard.viewRecentProjects": "project",
  "project.list": "project",
  "project.view": "project",
  "project.create": "project",
  "project.update": "project",
  "project.delete": "project",
  "project.viewBudget": "project",
  "project.updateBudget": "project",
  "project.viewParticipants": "project",
  "project.manageCollaborators": "project",
  "stage.view": "project",
  "stage.acceptBrief": "project",
  "stage.submitWork": "project",
  "stage.reviewSubmission": "project",
  "stage.requestRevision": "project",
  "stage.markSubmissionComplete": "project",
  "stage.markStageComplete": "project",
  "stage.updateBudget": "project",
  "stage.updateTimeline": "project",
  "chat.view": "project",
  "chat.comment": "project",
  "chat.uploadAttachment": "project",
  "chat.mentionUsers": "project",
  "compare.view": "project",
  "compare.comment": "project",
  "calendar.view": "calendar",
  "calendar.create": "calendar",
  "calendar.update": "calendar",
  "calendar.delete": "calendar",
  "calendar.assignParticipants": "calendar",
  "collaboration.viewDirectory": "collaboration",
  "collaboration.createUser": "collaboration",
  "collaboration.updateUser": "collaboration",
  "collaboration.deleteGlobal": "collaboration",
  "collaboration.manageModuleAccess": "collaboration",
  "collaboration.pauseVisibility": "collaboration",
  "library.view": "library",
  "library.deleteFile": "library",
  "archive.view": "archive",
  "archive.download": "archive",
  "completion.viewChecklist": "project",
  "completion.setApprovalRequired": "project",
  "completion.uploadApprovalProof": "project",
  "completion.setCopyrightTransfer": "project",
  "completion.uploadCopyrightDocument": "project",
  "completion.uploadInvoice": "project",
  "settings.viewOwnProfile": "settings",
  "settings.updateOwnProfile": "settings",
  "settings.changeOwnPassword": "settings",
  "settings.viewMasterData": "settings",
  "settings.manageMasterData": "settings",
  "settings.deleteMasterData": "settings",
  "settings.managePermissions": "settings",
  "notification.view": "notification",
  "notification.markRead": "notification",
  "file.view": "project",
  "file.download": "project",
  "file.delete": "project",
  "file.favorite": "project",
  "file.uploadSubmission": "project",
};

export const defaultRolePermissions: Record<PermissionRole, readonly PermissionKey[]> = {
  SUPER_ADMIN: allPermissionKeys.filter(
    (permission) => !contextOnlyPermissionKeys.includes(permission as ContextOnlyPermissionKey),
  ),
  ADMIN: [
    "dashboard.view",
    "dashboard.viewProjectCounts",
    "dashboard.viewRecentProjects",
    "project.list",
    "project.view",
    "project.create",
    "project.update",
    "project.viewParticipants",
    "project.manageCollaborators",
    "stage.view",
    "stage.acceptBrief",
    "stage.submitWork",
    "stage.reviewSubmission",
    "stage.requestRevision",
    "stage.markSubmissionComplete",
    "stage.markStageComplete",
    "stage.updateTimeline",
    "chat.view",
    "chat.comment",
    "chat.uploadAttachment",
    "chat.mentionUsers",
    "compare.view",
    "compare.comment",
    "calendar.view",
    "calendar.create",
    "calendar.update",
    "calendar.assignParticipants",
    "collaboration.viewDirectory",
    "collaboration.createUser",
    "collaboration.updateUser",
    "collaboration.manageModuleAccess",
    "collaboration.pauseVisibility",
    "library.view",
    "archive.view",
    "archive.download",
    "completion.viewChecklist",
    "completion.uploadApprovalProof",
    "completion.uploadCopyrightDocument",
    "completion.uploadInvoice",
    "settings.viewOwnProfile",
    "settings.updateOwnProfile",
    "settings.changeOwnPassword",
    "settings.viewMasterData",
    "settings.manageMasterData",
    "notification.view",
    "notification.markRead",
    "file.view",
    "file.download",
    "file.favorite",
    "file.uploadSubmission",
  ],
  COLLABORATOR: [
    "dashboard.view",
    "dashboard.viewProjectCounts",
    "dashboard.viewRecentProjects",
    "project.list",
    "project.view",
    "project.viewParticipants",
    "stage.view",
    "stage.acceptBrief",
    "stage.submitWork",
    "chat.view",
    "chat.comment",
    "chat.uploadAttachment",
    "chat.mentionUsers",
    "compare.view",
    "compare.comment",
    "calendar.view",
    "library.view",
    "archive.view",
    "archive.download",
    "completion.viewChecklist",
    "settings.viewOwnProfile",
    "settings.updateOwnProfile",
    "settings.changeOwnPassword",
    "notification.view",
    "notification.markRead",
    "file.view",
    "file.download",
    "file.favorite",
    "file.uploadSubmission",
  ],
};

export const defaultCollaboratorTypePermissions: Record<
  CollaboratorTypeValue,
  readonly PermissionKey[]
> = Object.fromEntries(
  collaboratorTypeValues.map((collaboratorType) => [collaboratorType, allPermissionKeys]),
) as unknown as Record<CollaboratorTypeValue, readonly PermissionKey[]>;

export const defaultAccessPresetPermissions: Record<
  ModuleAccessValue,
  readonly PermissionKey[]
> = {
  FULL: allPermissionKeys,
  LIMITED: allPermissionKeys,
  NONE: allPermissionKeys,
};

export const criticalSuperAdminPermissionKeys = [
  "dashboard.view",
  "collaboration.viewDirectory",
  "collaboration.createUser",
  "collaboration.updateUser",
  "collaboration.deleteGlobal",
  "collaboration.manageModuleAccess",
  "settings.viewOwnProfile",
  "settings.updateOwnProfile",
  "settings.changeOwnPassword",
  "settings.managePermissions",
  "notification.view",
] as const satisfies PermissionKey[];
